apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bn6o8vubi-nodejs 
  janus-idp.io/tekton: bn6o8vubi-nodejs
  backstage.io/kubernetes-id: bn6o8vubi-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bn6o8vubi-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml