apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bn6o8vubi-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bn6o8vubi-nodejs 
  name: bn6o8vubi-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bn6o8vubi-nodejs 
